### ISSUE TITLE
Feature request for localization

### ISSUE THREAD

**Issue by milotype** [Winbee/joplin-turn-to-chart#1]
I'm not a programmer, but maybe you could implement the posssibiity of translating/localizing some "standard" strings in the plug-in, such as:

`Legend`, `category`, `unit1`, `serie1 (unit1)`, dates like `Jan 03` (which are not common n different languages)

[Weblate](https://weblate.org/hr/) is a good translation platform for such things, but a separate `po` folder within your GitHub repository would also be ok.

Maybe you can think about it ...

**Comment by Winbee** [comment]
Hello @milotype, good point. I've implemented a way to pass the language as an option in the `v1.3.0` version. You can take a look at the doc here: https://github.com/Winbee/joplin-turn-to-chart#customlocale. With this option, the `legend` title and the dates will be translated.

The other element you mentioned (category, unit1, serie1 (unit1)) are coming from the user input directly so there is no need for translation.
