### ISSUE TITLE
how to use bar chart?

### ISSUE THREAD

**Issue by superiums** [Winbee/joplin-turn-to-chart#3]
the demo gif shows a bar chart but how did it appear instead of line chart ?

**Comment by deftdawg** [comment]
Wondered this myself, seems if it doesn't autodetect you can set the Axis type with: `xAxisType: category` and you'll get a bar chart. 🍻 

```turnToChart
Date | Hours |h2|
---------|------|--
"2022-06-13"|9|12
"2022-06-14"|9|23
"2022-06-15"|9|11
"2022-06-16"|8|11

xAxisType: category
```

**Comment by superiums** [comment]
thanks

在2022年6月16日 上午5:21:53 deftdawg ***@***.***>写道：
